Repository 2110503-2564/se-project-backend-3_veinscrum, pull requests merged in 2025-04, with the labels that each got.

#1 feat: add testing in jest, refactor and enhance code structure
  .env.example
  .prettierignore
  .prettierrc
  README.md
  dist/src/utils/filterAndPaginate.js
  dist/tsconfig.tsbuildinfo
  jest.config.ts
  package.json
  pnpm-lock.yaml
  src/app.ts
  src/constants/queryFields.ts
  src/controllers/auth.ts
  src/controllers/companies.ts
  src/controllers/interviewSessions.ts
  src/middleware/auth.ts
  src/models/Company.ts
  src/models/InterviewSession.ts
  src/models/User.ts
  src/routes/auth.ts
  src/routes/companies.ts
  src/routes/users.ts
  src/server.ts
  src/types/InterviewSession.d.ts
  src/types/Request.d.ts
  src/types/User.d.ts
  src/types/api/v1/sessions/POST.d.ts
  src/types/api/v1/sessions/PUT.d.ts
  src/utils/filterAndPaginate.ts
  tests/middleware/auth.ts
  tests/routes/auth.ts
  tests/routes/companies.ts
  tests/setup.ts
  tsconfig.json
Labels: bug, enhancement

#2 Feat: Update Companies + Job Listing
  .gitignore
  dist/tsconfig.tsbuildinfo
  jest.config.ts
  package-lock.json
  package.json
  src/app.ts
  src/controllers/auth.ts
  src/controllers/companies.ts
  src/controllers/interviewSessions.ts
  src/controllers/jobListings.ts
  src/middleware/auth.ts
  src/middleware/errorHandler.ts
  src/models/Company.ts
  src/models/InterviewSession.ts
  src/models/JobListing.ts
  src/models/User.ts
  src/routes/companies.ts
  src/routes/jobListings.ts
  src/types/Company.d.ts
  src/types/Global.d.ts
  src/types/InterviewSession.d.ts
  src/types/JobListing.d.ts
  src/types/User.d.ts
  src/utils/filterAndPaginate.ts
  tests/middleware/auth.test.ts
  tests/routes/auth.test.ts
  tests/routes/companies.test.ts
  tests/routes/companies.ts
  tests/setup.ts
Labels: bug, enhancement

#3 Feat: Add Docker Deployment
  .gitignore
  Dockerfile
  dist/config/db.js
  dist/src/constants/queryFields.js
  dist/src/controllers/auth.js
  dist/src/controllers/companies.js
  dist/src/controllers/interviewSessions.js
  dist/src/controllers/users.js
  dist/src/middleware/auth.js
  dist/src/middleware/errorHandler.js
  dist/src/models/Company.js
  dist/src/models/InterviewSession.js
  dist/src/models/User.js
  dist/src/routes/auth.js
  dist/src/routes/companies.js
  dist/src/routes/interviewSessions.js
  dist/src/routes/users.js
  dist/src/server.js
  dist/src/utils/buildComparisonQuery.js
  dist/src/utils/filterAndPaginate.js
  dist/tsconfig.tsbuildinfo
  docker-compose.yml
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/config/db.ts
  src/server.ts
  tsconfig.json
Labels: enhancement

#6 Refactor/better swagger and fix many bugs
  jest.config.ts
  src/app.ts
  src/controllers/interviewSessions.ts
  src/controllers/jobListings.ts
  src/controllers/users.ts
  src/middleware/errorHandler.ts
  src/routes/companies.ts
  src/routes/jobListings.ts
  src/swagger/definitions/schemas.ts
  src/swagger/index.ts
  src/swagger/routes/auth.routes.ts
  src/swagger/routes/companies.routes.ts
  src/swagger/routes/interview-sessions.routes.ts
  src/swagger/routes/job-listings.routes.ts
  src/swagger/routes/users.routes.ts
  tests/routes/companies.test.ts
  tests/routes/interviewSessions.test.ts
Labels: bug, documentation, enhancement

#9 Fix/fix validations
  src/controllers/companies.ts
  src/controllers/jobListings.ts
  src/swagger/routes/job-listings.routes.ts
  src/utils/filterAndPaginate.ts
  tests/routes/companies.test.ts
  tests/routes/jobListings.test.ts
Labels: bug, enhancement

#10 Feat/get interview sesions by company
  src/controllers/companies.ts
  src/controllers/interviewSessions.ts
  src/controllers/jobListings.ts
  src/models/Company.ts
  src/models/JobListing.ts
  src/routes/auth.ts
  src/routes/companies.ts
  src/routes/interviewSessions.ts
  src/routes/users.ts
  src/swagger/definitions/schemas.ts
  src/swagger/routes/companies.routes.ts
  src/swagger/routes/interview-sessions.routes.ts
  src/swagger/routes/job-listings.routes.ts
  tests/routes/interviewSessions.test.ts
Labels: bug, documentation, enhancement

#11 Fix/pagination and authorize level
  src/routes/interviewSessions.ts
  src/routes/jobListings.ts
  src/swagger/routes/companies.routes.ts
  src/swagger/routes/interview-sessions.routes.ts
  src/swagger/routes/job-listings.routes.ts
  src/utils/filterAndPaginate.ts
Labels: bug, documentation, enhancement

#12 Feat/websocket chat
  eslint.config.ts
  package.json
  pnpm-lock.yaml
  src/app.ts
  src/constants/ChatSocketEvent.ts
  src/controllers/auth.ts
  src/controllers/chats.ts
  src/controllers/companies.ts
  src/controllers/interviewSessions.ts
  src/controllers/jobListings.ts
  src/models/Chat.ts
  src/models/Company.ts
  src/models/InterviewSession.ts
  src/models/JobListing.ts
  src/models/User.ts
  src/routes/chats.ts
  src/routes/companies.ts
  src/server.ts
  src/socket/event/connection.ts
  src/socket/middleware/socketAuth.ts
  src/socket/middleware/socketChatValidatePermission.ts
  src/socket/socket.ts
  src/types/api/v1/chats/DELETE.d.ts
  src/types/api/v1/chats/PUT.d.ts
  src/types/models/Chat.d.ts
  src/types/models/Company.d.ts
  src/types/models/InterviewSession.d.ts
  src/types/models/JobListing.d.ts
  src/types/models/Message.d.ts
  src/types/models/PaginationResult.d.ts
  src/types/models/User.d.ts
  src/types/socket/SocketHandshakeQuery.d.ts
  src/types/socket/SocketWithAuth.d.ts
  src/types/socket/ValidatedChatSocket.d.ts
  src/utils/convertToSocketHandshakeQuery.ts
  src/utils/filterAndPaginate.ts
  tests/middleware/auth.test.ts
  tests/routes/companies.test.ts
  tests/routes/jobListings.test.ts
Labels: enhancement

#14 Fix/chat env
  package.json
  pnpm-lock.yaml
  src/controllers/chats.ts
  src/controllers/companies.ts
  src/controllers/interviewSessions.ts
  src/controllers/jobListings.ts
  src/server.ts
  src/socket/event/connection.ts
  src/socket/middleware/socketAuth.ts
  src/socket/middleware/socketChatValidatePermission.ts
  src/socket/socket.ts
  src/types/api/v1/chats/PUT.d.ts
  src/types/models/Chat.d.ts
  src/types/socket/SocketWithAuth.d.ts
  src/types/socket/ValidatedChatSocket.d.ts
  src/utils/convertToSocketHandshakeQuery.ts
  src/utils/filterAndPaginate.ts
Labels: bug

#15 Feat/flag
  src/app.ts
  src/controllers/flag.ts
  src/controllers/interviewSessions.ts
  src/models/Flag.ts
  src/routes/flag.ts
  src/routes/jobListings.ts
  src/socket/middleware/socketChatValidatePermission.ts
  src/swagger/definitions/schemas.ts
  src/swagger/routes/flag.routes.ts
  src/types/models/Flag.d.ts
  tests/routes/flags.test.ts
Labels: documentation, enhancement
